### ISSUE TITLE
TypeError exception when using export command

### ISSUE THREAD

**Issue by ohmer1** [nickjj/ansigenome#9]
I just installed ansigenome with pip install.  Don't know if use it correctly, but it crash when I try to export a graph.

> xxxx@xxxx:~/ansible/roles$ ansigenome export -o graph.png
Traceback (most recent call last):
  File "/usr/local/bin/ansigenome", line 326, in <module>
    main()
  File "/usr/local/bin/ansigenome", line 322, in main
    fn(args, options, reloaded_config, parser)
  File "/usr/local/bin/ansigenome", line 177, in execute_export
    Scan(args, options, config, export=True)
  File "/usr/local/lib/python2.7/dist-packages/ansigenome/scan.py", line 83, in __init__
    self.scan_roles()
  File "/usr/local/lib/python2.7/dist-packages/ansigenome/scan.py", line 117, in scan_roles
    self.report["roles"][key] = self.report_role(key)
  File "/usr/local/lib/python2.7/dist-packages/ansigenome/scan.py", line 190, in report_role
    "meta": self.gather_meta(),
  File "/usr/local/lib/python2.7/dist-packages/ansigenome/scan.py", line 213, in gather_meta
    dep_list.append(dependency["role"])
TypeError: string indices must be integers, not str

**Comment by julienvey** [comment]
#17 should fix the issue
